### ISSUE TITLE
Поиск в datatables

### ISSUE THREAD

**Issue by astrikov-d** [astrikov-d/dartcms#10]
Нужно реализовать простой и удобный поиск по таблицам. Возможно удобнее всего это будет делать на клиенте с помощью средств jquery easyui.

Пример: http://www.jeasyui.com/tutorial/datagrid/datagrid24.php

Искать нужно по строкам и датам.

**Comment by slavama** [comment]
Также нужен поиск по полям foreign_key и choices. Еще было бы хорошо сделать возможность autocomplete.
