### ISSUE TITLE
Обдумать и реализовать коцепцию public приложений

### ISSUE THREAD

**Issue by astrikov-d** [astrikov-d/dartcms#36]
Нужно создать базовую реализацию приложений.
Например для `feeds` - сделать набор вьюх и урлов для паблик части сайта. Список новостей, детальная страница, поддержка пейджинации и т.д.

**Comment by pc-mist** [comment]
Можно командами для manage.py сделать, что-то в духе
./manage py start_public_app <app_name> --views='<view_name_1>, <view_name_2>,...'
